config/routes.rb
Psqlproj::Application.routes.draw do
  
  resources :hotels do
    collection do 
      get :search
      get :search_result
    end
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
   root :to => 'hotels#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  attr_accessible :address, :city, :country, :latitude, :longitude, :name, :zipcode
  validates :address, :city, :country, :zipcode, :presence => true
  
  geocoded_by :address
  
  after_validation :geocode
  
#  def full_address
#    "#{address}, #{zipcode}, #{city}, #{country}"
#  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  def new
    @hotel = Hotel.new
  end
  
  def create
    @hotel = Hotel.new(params[:hotel])
    if @hotel.save
      redirect_to hotels_path
    else
      render :new
    end
  end
  
  def index
    @hotels = Hotel.find(:all)
  end
  
  def destroy
    @hotel = Hotel.find(params[:id])
    if @hotel.destroy
      redirect_to hotels_path
    end
  end
  
  def edit
    @hotel = Hotel.find(params[:id])
  end
  
  def update
    @hotel = Hotel.find(params[:id])
    if @hotel.update_attributes(params[:hotel])
      redirect_to hotels_path
    else
      render :edit
    end
  end
  
  def search
    
  end
  
  def search_result
    if params[:query].present?
      @hotel = Hotel.where("zipcode=?", "#{params[:query]}").first
      @hotels = Hotel.near(@hotel.zipcode)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<div>
  <p>Name: </p>
  <p>
    <%= f.text_field :name %>
  </p>
</div>

  <div>
    <p>Address: </p>
    <p>
      <%= f.text_field :address %>
    </p>
  </div>

  <div>
    <p>City: </p>
    <p>
      <%= f.text_field :city %>
    </p>
  </div>

  <div>
    <p>Country: </p>
    <p>
      <%= f.text_field :country %>
    </p>
  </div>

  <div>
    <p>Zipcode: </p>
    <p>
      <%= f.text_field :zipcode %>
    </p>
  </div>

<div>
  <%= f.submit %>
</div>

app/views/hotels/_search_result.html.erb
<% for hotel in @hotels %>
  <div class="row">
    <div class="well">
      <div class="col-sm-2">
        Hotel Name: 
      </div>
      <div class="col-sm-4">
        <%= hotel.name %>
      </div>
    </div>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<%= form_for @hotel, :method => "PUT" do |f| %>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end %>

app/views/hotels/index.html.erb
<div class="table-responsive">
  <table class="table table-hover">
    <tr class="success">
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>Country</th>
      <th>Zip code</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th>Status</th>
    </tr>

    <% @hotels.each do |hotel| %>
      <tr>
        <td>
          <%= hotel.name %>
        </td>
        <td>
          <%= hotel.address %> 
        </td>
        <td>
          <%= hotel.city %>
        </td>
        <td>
          <%= hotel.country %>
        </td>
        <td>
          <%= hotel.zipcode %>
        </td>
        <td>
          <%= hotel.longitude %>
        </td>
        <td>
          <%= hotel.latitude %>
        </td>
        <td>
          <%= link_to "delete", hotel_path(hotel.id), :method => :delete, :confirm => "are you sure to delete?" %>
        | <%= link_to "edit", edit_hotel_path(hotel.id) %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/hotels/new.html.erb
<%= form_for @hotel do |f| %>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end %>

app/views/hotels/search.html.erb
<div style="margin-left: 20px;">
  <p>Search Result from Geocoder</p>

  <%= form_tag search_result_hotels_path, :method => "GET", :remote => true do %>
    <div class="row">
      <div class="col-sm-4">
        <%= text_field_tag "query", "", :placeholder => "Search by Zipcode" %>
      </div>
      <div class="col-sm-2">
        <%= submit_tag "Search", :class => "btn btn-md btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

<div id="search">
  
</div>

app/views/hotels/search_result.js.erb
$("#search").html('<%= escape_javascript render :partial => "search_result" %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Psqlproj" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Psqlproj</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "hotels", hotels_path %></li>
              <li><%= link_to "Search Hotel", search_hotels_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Hotel</li>
              <li><%= link_to "hotels", hotels_path %></li>
              <li><%= link_to "Add New", new_hotel_path %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>
      
    </div> <!-- /container -->

  </body>
</html>